-- Ingredients Table
create table ingredients (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants(id) ON DELETE CASCADE,
  name text not null,
  unit text not null, -- 'kg', 'g', 'l', 'ml', 'pcs'
  current_stock numeric default 0,
  low_stock_threshold numeric default 5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Recipe Table (Linking Menu Items to Ingredients)
create table menu_item_ingredients (
  id bigint generated by default as identity primary key,
  menu_item_id bigint references menu_items(id) ON DELETE CASCADE,
  ingredient_id bigint references ingredients(id) ON DELETE CASCADE,
  quantity_required numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table ingredients enable row level security;
create policy "Public ingredients access" on ingredients for all using (true);

alter table menu_item_ingredients enable row level security;
create policy "Public menu_item_ingredients access" on menu_item_ingredients for all using (true);

-- Enable Realtime
alter publication supabase_realtime add table ingredients;
alter publication supabase_realtime add table menu_item_ingredients;
