-- ⚠️ IMPORTANT: Run this in your Supabase SQL Editor to enable the Reservations feature

-- 1. Create the reservations table
CREATE TABLE IF NOT EXISTS reservations (
    id bigint generated by default as identity primary key,
    restaurant_id bigint REFERENCES restaurants(id) ON DELETE CASCADE,
    table_id bigint REFERENCES tables(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT,
    customer_phone TEXT,
    party_size INTEGER NOT NULL CHECK (party_size > 0 AND party_size <= 50),
    reservation_date DATE NOT NULL,
    reservation_time TIME NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'seated', 'completed', 'cancelled', 'no-show')),
    special_requests TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Create the reservation_settings table
CREATE TABLE IF NOT EXISTS reservation_settings (
    restaurant_id bigint PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE,
    is_enabled BOOLEAN DEFAULT true,
    advance_booking_days INTEGER DEFAULT 30 CHECK (advance_booking_days > 0 AND advance_booking_days <= 365),
    slot_duration_minutes INTEGER DEFAULT 30 CHECK (slot_duration_minutes IN (15, 30, 60, 90, 120)),
    opening_time TIME DEFAULT '10:00:00',
    closing_time TIME DEFAULT '22:00:00',
    max_party_size INTEGER DEFAULT 12 CHECK (max_party_size > 0 AND max_party_size <= 50),
    require_phone BOOLEAN DEFAULT false,
    require_email BOOLEAN DEFAULT true,
    auto_confirm BOOLEAN DEFAULT true,
    booking_buffer_minutes INTEGER DEFAULT 0 CHECK (booking_buffer_minutes >= 0 AND booking_buffer_minutes <= 120),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_reservations_restaurant_date ON reservations(restaurant_id, reservation_date);
CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status);
CREATE INDEX IF NOT EXISTS idx_reservations_table ON reservations(table_id);
CREATE INDEX IF NOT EXISTS idx_reservations_datetime ON reservations(restaurant_id, reservation_date, reservation_time);

-- 4. Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc', NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 5. Create triggers for updated_at
DROP TRIGGER IF EXISTS update_reservations_updated_at ON reservations;
CREATE TRIGGER update_reservations_updated_at
    BEFORE UPDATE ON reservations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_reservation_settings_updated_at ON reservation_settings;
CREATE TRIGGER update_reservation_settings_updated_at
    BEFORE UPDATE ON reservation_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 6. Enable Row Level Security
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservation_settings ENABLE ROW LEVEL SECURITY;

-- 7. Create RLS Policies for reservations
-- Allow everyone to view reservations (needed for availability checking)
CREATE POLICY "Public reservations are viewable by everyone" 
    ON reservations FOR SELECT 
    USING (true);

-- Allow anyone to create reservations (customer bookings)
CREATE POLICY "Anyone can create reservations" 
    ON reservations FOR INSERT 
    WITH CHECK (true);

-- Allow restaurant owners to manage their reservations
CREATE POLICY "Owners can manage their reservations" 
    ON reservations FOR ALL 
    USING (true) 
    WITH CHECK (true);

-- 8. Create RLS Policies for reservation_settings
-- Allow everyone to view settings (needed for booking page)
CREATE POLICY "Public settings are viewable by everyone" 
    ON reservation_settings FOR SELECT 
    USING (true);

-- Allow restaurant owners to manage their settings
CREATE POLICY "Owners can manage their settings" 
    ON reservation_settings FOR ALL 
    USING (true) 
    WITH CHECK (true);

-- 9. Enable Realtime Updates
ALTER PUBLICATION supabase_realtime ADD TABLE reservations;
ALTER PUBLICATION supabase_realtime ADD TABLE reservation_settings;

-- 10. Insert default settings for existing restaurants
INSERT INTO reservation_settings (restaurant_id)
SELECT id FROM restaurants
ON CONFLICT (restaurant_id) DO NOTHING;

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'Reservation system tables created successfully!';
    RAISE NOTICE 'Tables: reservations, reservation_settings';
    RAISE NOTICE 'Default settings added for all existing restaurants';
END $$;
