-- Restaurants Table
create table restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  currency text default 'USD',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tables Table
create table tables (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants(id),
  name text not null,
  status text default 'available', -- available, occupied
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Menu Categories Table
create table menu_categories (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants(id) ON DELETE CASCADE,
  name text not null,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Menu Items Table
create table menu_items (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants(id),
  name text not null,
  price numeric not null,
  category text not null,
  description text,
  image_url text,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants(id),
  table_id bigint references tables(id),
  status text not null, -- pending, preparing, ready, served, paid
  total_amount numeric not null,
  order_type text default 'dine-in',
  customer_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Order Items Table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id),
  menu_item_id bigint references menu_items(id),
  name text not null, -- snapshot of name
  price numeric not null, -- snapshot of price
  quantity integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Open for Demo)
alter table restaurants enable row level security;
create policy "Public restaurants access" on restaurants for all using (true);

alter table tables enable row level security;
create policy "Public tables access" on tables for all using (true);

alter table menu_items enable row level security;
create policy "Public menu_items access" on menu_items for all using (true);

alter table menu_categories enable row level security;
create policy "Public menu_categories access" on menu_categories for all using (true);

alter table orders enable row level security;
create policy "Public orders access" on orders for all using (true);

alter table order_items enable row level security;
create policy "Public order_items access" on order_items for all using (true);

-- Enable RLS for banners
ALTER TABLE restaurant_banners ENABLE ROW LEVEL SECURITY;

-- Policies for banners
CREATE POLICY "Public banners are viewable by everyone" 
    ON restaurant_banners FOR SELECT 
    USING (true);

CREATE POLICY "Owners can manage their banners" 
    ON restaurant_banners FOR ALL 
    USING (true) 
    WITH CHECK (true);

-- Enable Realtime (Must be done AFTER table creation)
alter publication supabase_realtime add table orders;
alter publication supabase_realtime add table tables;
alter publication supabase_realtime add table restaurant_banners;
alter publication supabase_realtime add table menu_categories;
