-- ⚠️ IMPORTANT: Run this in your Supabase SQL Editor to enable the Banners feature

-- 1. Create the banners table (Corrected for BIGINT types)
CREATE TABLE IF NOT EXISTS restaurant_banners (
    id bigint generated by default as identity primary key,
    restaurant_id bigint REFERENCES restaurants(id) ON DELETE CASCADE,
    title TEXT,
    image_url TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Enable Security
ALTER TABLE restaurant_banners ENABLE ROW LEVEL SECURITY;

-- 3. Add Access Policies
-- Allow everyone to SEE banners
CREATE POLICY "Public banners are viewable by everyone" 
    ON restaurant_banners FOR SELECT 
    USING (true);

-- Allow owners to ADD/DELETE banners
CREATE POLICY "Owners can manage their banners" 
    ON restaurant_banners FOR ALL 
    USING (true) 
    WITH CHECK (true);

-- 4. Enable Realtime Updates
alter publication supabase_realtime add table restaurant_banners;
