-- ⚠️ IMPORTANT: Run this in your Supabase SQL Editor to enable Menu Categories

-- 1. Create the categories table
CREATE TABLE IF NOT EXISTS menu_categories (
    id bigint generated by default as identity primary key,
    restaurant_id bigint REFERENCES restaurants(id) ON DELETE CASCADE,
    name text not null,
    display_order integer default 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Enable Security
ALTER TABLE menu_categories ENABLE ROW LEVEL SECURITY;

-- 3. Add Access Policies
CREATE POLICY "Public menu_categories access" 
    ON menu_categories FOR ALL 
    USING (true)
    WITH CHECK (true);

-- 4. Enable Realtime Updates
alter publication supabase_realtime add table menu_categories;
